#include "node.h"
#include "printing.hpp"

int main(){
    Node a = Node('a');
    Node b = Node('b');
    Node one = Node(1);
    Node two = Node(2);

    print(a + b + one + two);
    print(a + b + one - two);
    print(a + b + one * two);
    print(a + b + one / two);
    print(a + b - one + two);
    print(a + b - one - two);
    print(a + b - one * two);
    print(a + b - one / two);
    print(a + b * one + two);
    print(a + b * one - two);
    print(a + b * one * two);
    print(a + b * one / two);
    print(a + b / one + two);
    print(a + b / one - two);
    print(a + b / one * two);
    print(a + b / one / two);
    print(a - b + one + two);
    print(a - b + one - two);
    print(a - b + one * two);
    print(a - b + one / two);
    print(a - b - one + two);
    print(a - b - one - two);
    print(a - b - one * two);
    print(a - b - one / two);
    print(a - b * one + two);
    print(a - b * one - two);
    print(a - b * one * two);
    print(a - b * one / two);
    print(a - b / one + two);
    print(a - b / one - two);
    print(a - b / one * two);
    print(a - b / one / two);
    print(a * b + one + two);
    print(a * b + one - two);
    print(a * b + one * two);
    print(a * b + one / two);
    print(a * b - one + two);
    print(a * b - one - two);
    print(a * b - one * two);
    print(a * b - one / two);
    print(a * b * one + two);
    print(a * b * one - two);
    print(a * b * one * two);
    print(a * b * one / two);
    print(a * b / one + two);
    print(a * b / one - two);
    print(a * b / one * two);
    print(a * b / one / two);
    print(a / b + one + two);
    print(a / b + one - two);
    print(a / b + one * two);
    print(a / b + one / two);
    print(a / b - one + two);
    print(a / b - one - two);
    print(a / b - one * two);
    print(a / b - one / two);
    print(a / b * one + two);
    print(a / b * one - two);
    print(a / b * one * two);
    print(a / b * one / two);
    print(a / b / one + two);
    print(a / b / one - two);
    print(a / b / one * two);
    print(a / b / one / two);
    return 0;
}