
  // This file is generated by template_generator.py
  #include <array>

  using op = int(int, int);
  const auto all_expressions = std::to_array<size_t>({0b011, 0b00111, 0b01011, 0b0001111, 0b0010111, 0b0011011, 0b0100111, 0b0101011, 0b000011111, 0b000101111, 0b000110111, 0b000111011, 0b001001111, 0b001010111, 0b001011011, 0b001100111, 0b001101011, 0b010001111, 0b010010111, 0b010011011, 0b010100111, 0b010101011, 0b00000111111, 0b00001011111, 0b00001101111, 0b00001110111, 0b00001111011, 0b00010011111, 0b00010101111, 0b00010110111, 0b00010111011, 0b00011001111, 0b00011010111, 0b00011011011, 0b00011100111, 0b00011101011, 0b00100011111, 0b00100101111, 0b00100110111, 0b00100111011, 0b00101001111, 0b00101010111, 0b00101011011, 0b00101100111, 0b00101101011, 0b00110001111, 0b00110010111, 0b00110011011, 0b00110100111, 0b00110101011, 0b01000011111, 0b01000101111, 0b01000110111, 0b01000111011, 0b01001001111, 0b01001010111, 0b01001011011, 0b01001100111, 0b01001101011, 0b01010001111, 0b01010010111, 0b01010011011, 0b01010100111, 0b01010101011});

  size_t func(int a, int b, int c, int d, int e, int f, op op1, op op2, op op3, op op4, op op5, int goal){
    size_t res = 0;

  	res |= static_cast<size_t>(goal == op1(a, b)) << 0; // 011
	res |= static_cast<size_t>(goal == op2(a, op1(b, c))) << 1; // 00111
	res |= static_cast<size_t>(goal == op2(op1(a, b), c)) << 2; // 01011
	res |= static_cast<size_t>(goal == op3(a, op2(b, op1(c, d)))) << 3; // 0001111
	res |= static_cast<size_t>(goal == op3(a, op2(op1(b, c), d))) << 4; // 0010111
	res |= static_cast<size_t>(goal == op3(op1(a, b), op2(c, d))) << 5; // 0011011
	res |= static_cast<size_t>(goal == op3(op2(a, op1(b, c)), d)) << 6; // 0100111
	res |= static_cast<size_t>(goal == op3(op2(op1(a, b), c), d)) << 7; // 0101011
	res |= static_cast<size_t>(goal == op4(a, op3(b, op2(c, op1(d, e))))) << 8; // 000011111
	res |= static_cast<size_t>(goal == op4(a, op3(b, op2(op1(c, d), e)))) << 9; // 000101111
	res |= static_cast<size_t>(goal == op4(a, op3(op1(b, c), op2(d, e)))) << 10; // 000110111
	res |= static_cast<size_t>(goal == op4(op1(a, b), op3(c, op2(d, e)))) << 11; // 000111011
	res |= static_cast<size_t>(goal == op4(a, op3(op2(b, op1(c, d)), e))) << 12; // 001001111
	res |= static_cast<size_t>(goal == op4(a, op3(op2(op1(b, c), d), e))) << 13; // 001010111
	res |= static_cast<size_t>(goal == op4(op1(a, b), op3(op2(c, d), e))) << 14; // 001011011
	res |= static_cast<size_t>(goal == op4(op2(a, op1(b, c)), op3(d, e))) << 15; // 001100111
	res |= static_cast<size_t>(goal == op4(op2(op1(a, b), c), op3(d, e))) << 16; // 001101011
	res |= static_cast<size_t>(goal == op4(op3(a, op2(b, op1(c, d))), e)) << 17; // 010001111
	res |= static_cast<size_t>(goal == op4(op3(a, op2(op1(b, c), d)), e)) << 18; // 010010111
	res |= static_cast<size_t>(goal == op4(op3(op1(a, b), op2(c, d)), e)) << 19; // 010011011
	res |= static_cast<size_t>(goal == op4(op3(op2(a, op1(b, c)), d), e)) << 20; // 010100111
	res |= static_cast<size_t>(goal == op4(op3(op2(op1(a, b), c), d), e)) << 21; // 010101011
	res |= static_cast<size_t>(goal == op5(a, op4(b, op3(c, op2(d, op1(e, f)))))) << 22; // 00000111111
	res |= static_cast<size_t>(goal == op5(a, op4(b, op3(c, op2(op1(d, e), f))))) << 23; // 00001011111
	res |= static_cast<size_t>(goal == op5(a, op4(b, op3(op1(c, d), op2(e, f))))) << 24; // 00001101111
	res |= static_cast<size_t>(goal == op5(a, op4(op1(b, c), op3(d, op2(e, f))))) << 25; // 00001110111
	res |= static_cast<size_t>(goal == op5(op1(a, b), op4(c, op3(d, op2(e, f))))) << 26; // 00001111011
	res |= static_cast<size_t>(goal == op5(a, op4(b, op3(op2(c, op1(d, e)), f)))) << 27; // 00010011111
	res |= static_cast<size_t>(goal == op5(a, op4(b, op3(op2(op1(c, d), e), f)))) << 28; // 00010101111
	res |= static_cast<size_t>(goal == op5(a, op4(op1(b, c), op3(op2(d, e), f)))) << 29; // 00010110111
	res |= static_cast<size_t>(goal == op5(op1(a, b), op4(c, op3(op2(d, e), f)))) << 30; // 00010111011
	res |= static_cast<size_t>(goal == op5(a, op4(op2(b, op1(c, d)), op3(e, f)))) << 31; // 00011001111
	res |= static_cast<size_t>(goal == op5(a, op4(op2(op1(b, c), d), op3(e, f)))) << 32; // 00011010111
	res |= static_cast<size_t>(goal == op5(op1(a, b), op4(op2(c, d), op3(e, f)))) << 33; // 00011011011
	res |= static_cast<size_t>(goal == op5(op2(a, op1(b, c)), op4(d, op3(e, f)))) << 34; // 00011100111
	res |= static_cast<size_t>(goal == op5(op2(op1(a, b), c), op4(d, op3(e, f)))) << 35; // 00011101011
	res |= static_cast<size_t>(goal == op5(a, op4(op3(b, op2(c, op1(d, e))), f))) << 36; // 00100011111
	res |= static_cast<size_t>(goal == op5(a, op4(op3(b, op2(op1(c, d), e)), f))) << 37; // 00100101111
	res |= static_cast<size_t>(goal == op5(a, op4(op3(op1(b, c), op2(d, e)), f))) << 38; // 00100110111
	res |= static_cast<size_t>(goal == op5(op1(a, b), op4(op3(c, op2(d, e)), f))) << 39; // 00100111011
	res |= static_cast<size_t>(goal == op5(a, op4(op3(op2(b, op1(c, d)), e), f))) << 40; // 00101001111
	res |= static_cast<size_t>(goal == op5(a, op4(op3(op2(op1(b, c), d), e), f))) << 41; // 00101010111
	res |= static_cast<size_t>(goal == op5(op1(a, b), op4(op3(op2(c, d), e), f))) << 42; // 00101011011
	res |= static_cast<size_t>(goal == op5(op2(a, op1(b, c)), op4(op3(d, e), f))) << 43; // 00101100111
	res |= static_cast<size_t>(goal == op5(op2(op1(a, b), c), op4(op3(d, e), f))) << 44; // 00101101011
	res |= static_cast<size_t>(goal == op5(op3(a, op2(b, op1(c, d))), op4(e, f))) << 45; // 00110001111
	res |= static_cast<size_t>(goal == op5(op3(a, op2(op1(b, c), d)), op4(e, f))) << 46; // 00110010111
	res |= static_cast<size_t>(goal == op5(op3(op1(a, b), op2(c, d)), op4(e, f))) << 47; // 00110011011
	res |= static_cast<size_t>(goal == op5(op3(op2(a, op1(b, c)), d), op4(e, f))) << 48; // 00110100111
	res |= static_cast<size_t>(goal == op5(op3(op2(op1(a, b), c), d), op4(e, f))) << 49; // 00110101011
	res |= static_cast<size_t>(goal == op5(op4(a, op3(b, op2(c, op1(d, e)))), f)) << 50; // 01000011111
	res |= static_cast<size_t>(goal == op5(op4(a, op3(b, op2(op1(c, d), e))), f)) << 51; // 01000101111
	res |= static_cast<size_t>(goal == op5(op4(a, op3(op1(b, c), op2(d, e))), f)) << 52; // 01000110111
	res |= static_cast<size_t>(goal == op5(op4(op1(a, b), op3(c, op2(d, e))), f)) << 53; // 01000111011
	res |= static_cast<size_t>(goal == op5(op4(a, op3(op2(b, op1(c, d)), e)), f)) << 54; // 01001001111
	res |= static_cast<size_t>(goal == op5(op4(a, op3(op2(op1(b, c), d), e)), f)) << 55; // 01001010111
	res |= static_cast<size_t>(goal == op5(op4(op1(a, b), op3(op2(c, d), e)), f)) << 56; // 01001011011
	res |= static_cast<size_t>(goal == op5(op4(op2(a, op1(b, c)), op3(d, e)), f)) << 57; // 01001100111
	res |= static_cast<size_t>(goal == op5(op4(op2(op1(a, b), c), op3(d, e)), f)) << 58; // 01001101011
	res |= static_cast<size_t>(goal == op5(op4(op3(a, op2(b, op1(c, d))), e), f)) << 59; // 01010001111
	res |= static_cast<size_t>(goal == op5(op4(op3(a, op2(op1(b, c), d)), e), f)) << 60; // 01010010111
	res |= static_cast<size_t>(goal == op5(op4(op3(op1(a, b), op2(c, d)), e), f)) << 61; // 01010011011
	res |= static_cast<size_t>(goal == op5(op4(op3(op2(a, op1(b, c)), d), e), f)) << 62; // 01010100111
	res |= static_cast<size_t>(goal == op5(op4(op3(op2(op1(a, b), c), d), e), f)) << 63; // 01010101011
	return res;
}

